version: '3'
services:
  training:
    image: fraud-detection-system:latest
    container_name: my_fraud_detection_train_container
    command: train
    volumes:
      - ./assets:/fraud-detection-system/assets
      - ./.cachedir:/fraud-detection-system/.cachedir
  deployment:
    image: fraud-detection-system:latest
    container_name: my_fraud_detection_test_container
    command: test_deployment
    depends_on:
      - training
    volumes:
      - ./assets:/fraud-detection-system/assets
  serve_dev:
    image: fraud-detection-system:latest
    container_name: my_fraud_detection_serve_container
    command: serve_dev
    ports:
      - "8000:8000"
    depends_on:
      - deployment
    volumes:
      - ./assets:/fraud-detection-system/assets
